# Generated by Django 4.2.4 on 2023-09-13 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0004_remove_post_date_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
