# Generated by Django 4.2.4 on 2023-09-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0009_rename_post_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="upload_to",
        ),
    ]
