# Generated by Django 4.2.4 on 2023-09-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0010_remove_blogpost_upload_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
