# Generated by Django 4.2.4 on 2023-09-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0012_rename_blogpost_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="imagees"),
        ),
    ]
