# Generated by Django 4.2.4 on 2023-09-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0017_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
