# Generated by Django 4.2.4 on 2023-09-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0019_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Users",
        ),
    ]
