# Generated by Django 4.2.4 on 2023-09-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0021_rename_users_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=30),
        ),
    ]
