# Generated by Django 4.2.4 on 2023-09-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0023_remove_post_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post_data',
        ),
    ]
