# Generated by Django 4.2.4 on 2023-10-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0027_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
