# Generated by Django 4.2.4 on 2023-10-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0028_delete_category_remove_post_category"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table=None,
        ),
    ]
