# Generated by Django 4.2.4 on 2023-10-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0029_alter_post_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="post_data",
        ),
    ]
