# Generated by Django 4.2.4 on 2023-10-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0030_alter_post_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="blog_id",
            new_name="id",
        ),
    ]
