# Generated by Django 4.2.4 on 2023-10-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0031_rename_blog_id_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
