# Generated by Django 4.2.4 on 2023-10-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0032_alter_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="header_image",
        ),
    ]
