# Generated by Django 4.2.4 on 2023-10-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0033_remove_post_header_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, max_length=9000, null=True),
        ),
    ]
