# Generated by Django 4.2.4 on 2023-10-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0035_post_snippet_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
