# Generated by Django 4.2.4 on 2023-10-16 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Myapp", "0037_post_title_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/profile/"
                    ),
                ),
                (
                    "website_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "facebook_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "twitter_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Instagram_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
