# Generated by Django 4.2.4 on 2023-10-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0039_remove_profile_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Write your bio here', max_length=255),
        ),
    ]
