# Generated by Django 4.2.4 on 2023-10-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0041_remove_post_header_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(default="Write your bio here", max_length=4000),
        ),
    ]
