# Generated by Django 4.2.4 on 2023-10-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0045_alter_post_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="linkedin_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
