# Generated by Django 4.2.4 on 2023-10-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0046_profile_linkedin_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="linkedin_url",
        ),
    ]
